episodeLength: 1
weather: false
map:
    size: 1700
    wall:
        height: 128
        block: 7
daylightCycle:
    do: false
    time: 6000
scoreboard: Switch The Patrick
kick-on-death:
    kick: true
    time: 30
naturalRegen: false
switch:
    number: 3
    1:
        episode: 2
        time: 10
    2:
        episode: 3
        time: 10
    3:
        episode: 4
        time: 10