episodeLength: 1
weather: false
map:
    size: 1700
    wall:
        height: 128
        block: 7
daylightCycle:
    do: false
    time: 6000
scoreboard: Switch The Patrick
kick-on-death:
    kick: true
    time: 30
naturalRegen: false